---
# tasks file for nginx_ssl_multios

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_packages.
  set_fact:
    nginx_packages: "{{ __nginx_packages | list }}"
  when: nginx_packages is not defined

- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Configure Nginx.
  include_tasks: "configure-{{ ansible_os_family }}.yml"